### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by barissenkal** [react-native-community/jsc-android-buildscripts#100]
### Issue Description

````
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 16 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang++ src.cpp
````

### Version, config, any additional info

Android 9.0
CMake 3.10.2
NDK 19.2.5345600

**Comment by Kudo** [comment]
@barissenkal NDK r19 changes a lot especially the [in-place build](https://developer.android.com/ndk/guides/other_build_systems) and is not supported in the meantime.

We use NDK r17c which aligned with current React Native NDK version.
Please try with NDK r17c.
