### ISSUE TITLE
Performance regressions with 241213.2.0

### ISSUE THREAD

**Issue by benoitdion** [react-native-community/jsc-android-buildscripts#112]
#108 improved stability of the JSC on android significantly but did cause major performance regression from the version shipping with RN 0.59. Opening this issue to track what can be done to restore performance (re-enable JIT with a bug fix?)

**Comment by Kudo** [comment]
#114 enabled JIT back and even got some performance improvement from 241213 no-DFG JIT version.
I am going to close this. Thanks @benoitdion.
