### ISSUE TITLE
Could not find org.webkit:android-jsc:r241213.

### ISSUE THREAD

**Issue by jacquesdev** [react-native-community/jsc-android-buildscripts#115]
# Bug

I followed the instructions for react-native 0.59 (https://github.com/react-native-community/jsc-android-buildscripts#for-react-native-version-059), using master

I get this error when building

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDevDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find org.webkit:android-jsc:r241213.
     Searched in the following locations:
       - file:/Users/user/.m2/repository/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - file:/Users/user/.m2/repository/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
       - https://dl.google.com/dl/android/maven2/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - https://dl.google.com/dl/android/maven2/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
       - https://jcenter.bintray.com/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - https://jcenter.bintray.com/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
       - file:/Users/user/dev/native/node_modules/react-native/android/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - file:/Users/user/dev/native/node_modules/react-native/android/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
       - file:/Users/user/dev/native/node_modules/jsc-android/dist/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - file:/Users/user/dev/native/node_modules/jsc-android/dist/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
       - https://maven.fabric.io/public/org/webkit/android-jsc/r241213/android-jsc-r241213.pom
       - https://maven.fabric.io/public/org/webkit/android-jsc/r241213/android-jsc-r241213.jar
     Required by:
         project :app

**Comment by Kudo** [comment]
@jacquesdev May I know your jsc-android version in package.json and maybe yarn.lock?

**Comment by jacquesdev** [comment]
I ended up installing `jsc-android@next` and then following these steps, https://gist.github.com/Kudo/cc40662163fbd69dd01d66fd99476c17#file-steps_for_webkitgtk_2_24_2-md, which worked.

Feel free to close this issue

**Comment by Kudo** [comment]
Thank you. I am going to close this and feel free to let us know if your encounter other issues.
