### ISSUE TITLE
use 'deprecated-react-native-listview' js engine: hermes

### ISSUE THREAD

**Issue by HadisSharif** [react-native-community/jsc-android-buildscripts#118]
after adding hermes code in app/build.gradle when I run the project, this error pops up.
I added this part at the top of the file:
project.ext.react = [
    entryFile: "index.js",
      enableHermes: true,
]
def jscFlavor = 'org.webkit:android-jsc:r174650'
def enableHermes = project.ext.react.get("enableHermes", false);

and this part in dependencies:
 if (enableHermes) {
      println 'Hermes is enabled'
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
           imp

I couldn't fine any solution so far.
![Screenshot_1563684077](https://user-images.githubusercontent.com/16177020/61587057-9e8d9100-ab97-11e9-8bce-a5faf8f7620d.png)

**Comment by skantus** [comment]
Hi @HadisSharif,

You could use `deprecated-react-native-listview`.

**Comment by Kudo** [comment]
As @skantus said, the issue might come from new RN Lean Core design and move some components into separated packages.
I am going to close this issue as this is not related to JSC.
If you still encounter issues from JSC, please feel free to let me know.
