### ISSUE TITLE
React Native `v0.71.0` uses an outdated version of `jsc-android` (NDKs mismatch and causes crash)

### ISSUE THREAD

**Issue by kraenhansen** [react-native-community/jsc-android-buildscripts#178]
### Issue Description

As outlined in https://github.com/facebook/react-native/issues/36052 there's a mismatch in NDK between the RN template app at `v0.71.0` and the `250230.2.1` version of `jsc-android`. Upgrading React Native to use `v294992.0.0` of `jsc-android` seems to relieve the issue, but this is not `latest` on NPM and marked as a pre-release on GitHub.

Another potential fix is to publish a release of `250230.2.1` build with an updated NDK, matching that of the RN template app.

**Comment by Kudo** [comment]
closed via #179
