### ISSUE TITLE
Possible to merge some work with Upstream Webkit? 

### ISSUE THREAD

**Issue by fxfactorial** [react-native-community/jsc-android-buildscripts#24]
Webkit people have told me that they would be okay with accepting patching that are JSCOnly port, because then upstream can do things like it will be possible to have buildbot and run tests, to prevent regressions.

**Comment by annulen** [comment]
FWIW, I've just committed proper fix for issue corresponding to https://github.com/SoftwareMansion/jsc-android-buildscripts/blob/master/patches/intl/icu-disabled.patch (see https://trac.webkit.org/changeset/228136)
