### ISSUE TITLE
ERROR ON RUNNING NPM RUN START

### ISSUE THREAD

**Issue by faisalpathan** [react-native-community/jsc-android-buildscripts#76]
### Issue Description

jsc-android-buildscripts/scripts/compile/toolchain.sh: line 9: /Users/*name*/Library/Android/sdk:/ndk-bundle/build/tools/make_standalone_toolchain.py: No such file or directory

### Version, config, any additional info

Installed all required packages mentioned in README

**Comment by DanielZlotin** [comment]
`/Users/name/Library/Android/sdk:/ndk-bundle/build/tools/make_standalone_toolchain.py`
Is this the correct path to android ndk? seems like you have an extra `:` there
